### ISSUE TITLE
accn.py depends on BatchedDGLHeteroGraph, which is no longer in dgl 5.0

### ISSUE THREAD

**Issue by charlesmartin14** [awslabs/dgl-lifesci#70] opened 2020-08-22 05:59 UTC
accn.py depends on BatchedDGLHeteroGraph, which is no longer in dgl 5.0

**Comment by mufeili** [comment] 2020-08-24 06:11
Thank you for your report. This should be fixed with the master branch. Can you git clone the repo and try installing from source?

**Comment by x94carbone** [comment] 2020-08-24 20:12
Same issue for the `MPNNPredictor`. @mufeili, using a previous version of `dgllife` works (unsure if it's the version on `master` but I think it's clear what the issue is here). Any thoughts when this fix will be pushed to production? It's breaking my CI pipeline 👍

**Comment by mufeili** [comment] 2020-08-25 07:41
> Same issue for the `MPNNPredictor`. @mufeili, using a previous version of `dgllife` works (unsure if it's the version on `master` but I think it's clear what the issue is here). Any thoughts when this fix will be pushed to production? It's breaking my CI pipeline 👍

Sorry for breaking your CI pipeline. Can you first try installing from source and see if it addresses your issues locally? If so, I can make a minor release for the patch.

**Comment by x94carbone** [comment] 2020-08-25 12:41
@mufeili No worries about the CI pipeline, that can wait and I can run essential unit checks locally as you're implying. The previous version of `dgllife` works just fine on my local machine, I just won't update. Just was curious about what the timeline is for a patch is all. Thanks for the quick responses!

**Comment by mufeili** [comment] 2020-08-25 19:38
> @mufeili No worries about the CI pipeline, that can wait and I can run essential unit checks locally as you're implying. The previous version of `dgllife` works just fine on my local machine, I just won't update. Just was curious about what the timeline is for a patch is all. Thanks for the quick responses!

@x94carbone I don't mind making a minor release anytime. That only requires uploading built distributions to PyPI and Conda. If your local unit checks work well, I can make a minor release for the patch right after that.

**Comment by x94carbone** [comment] 2020-08-25 21:23
@mufeili No worries. I had no problems installing from source and that is a perfectly fine solution for me for now. Thank you for your help, much appreciated!

**Closed** 2020-09-01 03:15 UTC
