### ISSUE TITLE
Scikit-learn dependency for 0.3.0

### ISSUE THREAD

**Issue by ryotatomioka** [awslabs/dgl-lifesci#204] opened 2022-12-21 08:39 UTC
On Python3.10 and `pip==22.3.1`, the following fails
```bash
$ pip install 'dgllife==0.3.0' 'scikit-learn>=1.0'
```
due to the error
>ERROR: Cannot install dgllife==0.3.0 and scikit-learn>=1.0 because these package versions have conflicting dependencies.
>
>The conflict is caused by:
>   The user requested scikit-learn>=1.0
>  dgllife 0.3.0 depends on scikit-learn<1.0 and >=0.22.2

However this was ok for 0.2.9.
```bash
$ pip install 'dgllife==0.2.9' 'scikit-learn>=1.0'
```

Is this a real change in dependency, or is it caused by buggy metadata?

**Comment by mufeili** [comment] 2022-12-21 13:19
This is a duplicate of #197 and should have been fixed by the latest `0.3.1` release. Feel free to reopen the issue if it still exists. Thanks.

**Closed by mufeili** 2022-12-21 13:19 UTC
